name: test_template_1755184322741
description: Test template
category: document
template_info:
  name: test_template_1755184322741
  description: Test template description
  category: custom
  version: 1.0.0
  created_at: '2025-08-14T08:12:02.741698'
  features: []
  required_assets: []
  optional_assets: []
