name: unique_test_template
description: Test template
category: document
template_info:
  name: unique_test_template
  description: Test template description
  category: custom
  version: 1.0.0
  created_at: '2025-08-13T22:00:33.631302'
  features: []
  required_assets: []
  optional_assets: []
