name: test_template_1755181332873
description: Test template
category: document
template_info:
  name: test_template_1755181332873
  description: Test template description
  category: custom
  version: 1.0.0
  created_at: '2025-08-14T07:22:12.873639'
  features: []
  required_assets: []
  optional_assets: []
