name: test_template_1755189893795
description: Test template
category: document
template_info:
  name: test_template_1755189893795
  description: Test template description
  category: custom
  version: 1.0.0
  created_at: '2025-08-14T09:44:53.795873'
  features: []
  required_assets: []
  optional_assets: []
